- name: update packages
  command: "sudo apt update -y"
  
- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: java repo
  command: "sudo apt install openjdk-8-jdk -y"

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: get jenkins key
  shell: "wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -"

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: add jenkins repo
  command: "sudo apt-add-repository \"deb http://pkg.jenkins-ci.org/debian binary/\" -y"

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: install jenkins
  command: "sudo apt install jenkins -y"

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: certbot repo
  command: "sudo add-apt-repository ppa:certbot/certbot -y"

- name: install nginx
  command: "sudo apt install -y nginx python-certbot-nginx"

- name: Copy nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
    group: root
    owner: root
    mode: 0644

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: Timeout configuration
  copy:
    src: timeout.conf
    dest: /etc/nginx/conf.d/
    group: root
    owner: root
    mode: 0644

- name: nginx config1
  command: sudo nginx -t

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: nginx restart
  command: sudo systemctl restart nginx

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: certbot config
  command: sudo certbot --nginx -d "{{dns_zone}}" --agree-tos --register-unsafely-without-email -n

- name: Docker Installation - adding docker repository
  shell: |
    # sudo apt-get remove docker docker-engine docker.io containerd runc
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  register: docker_registery_info
- debug:
    var: docker_registery_info

- name: install maven
  command: sudo apt install maven -y

- name: wait for 5 sec
  wait_for:
    delay: 5
    timeout: 0

- name: Docker Installation - repository installation
  shell: |
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    sudo apt install -y gnupg2 pass
    sudo groupadd docker
    sudo usermod -aG docker jenkins
    sudo chmod 666 /var/run/docker.sock
  register: docker_registery_installation_info
- debug:
    var: docker_registery_installation_info

